[project]
name = "rajk_appman"
description = "Rajk django app management"
authors = [
    "Endre Márk Borza"
]
license = "MIT"
readme = "README.md"
python = ">=3.6"
url = "https://github.com/rajk-apps/rajk-appman"
keywords="ci/cd"